site_name: QNATK
nav:
- Home: index.md
- Frontend: 
    - Basics: qnatk-q.md
    - Composibles:
        - useForm: useForm.md
        - useDatatables: useDatatables.md
- Backend: 
    - Basics: qnatk-n.md
    
theme: readthedocs
markdown_extensions:
  - admonition