site_name: QNATK
nav:
- Home: index.md
- Frontend: 
    - Basics: qnatk-q.md
    - Composibles:
        - useForm: useForm.md
        - useDatatables: useDatatables.md
- Backend: 
    - Basics: qnatk-n.md
    - Hook-system: hooklist.md
    - Pre-made Api: api.md
theme: readthedocs
markdown_extensions:
  - admonition