site_name: QNATK
nav:
- Home: index.md
- Frontend: 
    - Basics: qnatk-q.md
    - Composibles : composibles.md
- Backend: 
    - Basics: qnatk-n.md
    
theme: readthedocs
markdown_extensions:
  - admonition